Deu erro após editar "settings.py" incluindo:
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'agenda.core',   <------------------------ Erro começou após incluir essa linha
]

Para resolver, editei o apps.py e:
class CoreConfig(AppConfig):
    default_auto_field = 'django.db.models.BigAutoField'
    name = 'agenda.core'  <-------- Deixei assim!

==============================================================
para acessar /admin
usuario: juliano.valente
senha: senha